apiVersion: ratelimit.zufardhiyaulhaq.com/v1alpha1
kind: LocalRateLimitConfig
metadata:
  name: podinfo
  namespace: development
spec:
  type: "sidecar"
  selector:
    labels:
      app: podinfo
    istio_version:
      - "1.18"
      - "1.19"
      - "1.20"
      - "1.21"
