# permissions for end users to view globalratelimitconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalratelimitconfig-viewer-role
rules:
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - globalratelimitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - globalratelimitconfigs/status
  verbs:
  - get
