# permissions for end users to edit globalratelimits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalratelimit-editor-role
rules:
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - globalratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - globalratelimits/status
  verbs:
  - get
