# permissions for end users to edit globalratelimitconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: globalratelimitconfig-editor-role
rules:
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - globalratelimitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.zufardhiyaulhaq.com
  resources:
  - globalratelimitconfigs/status
  verbs:
  - get
