apiVersion: v1
entries:
  istio-ratelimit-operator:
  - apiVersion: v2
    appVersion: 2.5.0
    created: "2022-06-27T01:20:30.04325+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 46af5b28ac5ffaddfe0d06753241abc6e6988106b18077e928754e8c5c2071b4
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v2
    appVersion: 2.4.0
    created: "2022-06-27T01:20:30.041794+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 08668539d33ca54907a6836a60bbc30cb91cc8dee7ba870f97f73e7dc2b69931
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v2
    appVersion: 2.3.0
    created: "2022-06-27T01:20:30.037952+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: ac0e11ecdeffa4fe656c17f3588d1880391477d9af56ce7165d3e6237ee2a170
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 2.2.0
    created: "2022-06-27T01:20:30.02875+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a2979dd17de57397f8b21b8c8e91ec7024d61d9e27ebfe6329f2461dbf00daa4
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 2.1.0
    created: "2022-06-27T01:20:30.020761+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 8e2589c35c4cdae7e1ae4c36d63927d1643f12c935eed81a1a8870f5b8472bbc
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-06-27T01:20:30.017958+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: 4950de5d1f4ef8b304a21938d317b9abc2380cf41143fd9b9a8ebfcd073ea273
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2022-06-27T01:20:30.016601+07:00"
    description: Istio ratelimit operator provide an easy way to configure Global
      or Local Ratelimit in Istio mesh. Istio ratelimit operator also support EnvoyFilter
      versioning!
    digest: a25e113e0de29a78de29262f5043a9db260eab8287f9a1facd732ba764da7d6a
    home: https://github.com/zufardhiyaulhaq/istio-ratelimit-operator
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-ratelimit-operator
    type: application
    urls:
    - istio-ratelimit-operator-1.0.0.tgz
    version: 1.0.0
generated: "2022-06-27T01:20:30.014792+07:00"
